# Generated by Django 6.0.2 on 2026-02-09 12:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=20)),
                ('message_open', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', '남'), ('F', '여')], max_length=1)),
                ('pin_hash', models.CharField(max_length=128)),
                ('received_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.event')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.event')),
                ('from_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='game.participant')),
                ('to_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='game.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.event')),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p1', to='game.participant')),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p2', to='game.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.event')),
                ('from_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_signals', to='game.participant')),
                ('to_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_signals', to='game.participant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('event', 'nickname'), name='uniq_event_nickname'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['event', 'to_participant', 'created_at'], name='game_messag_event_i_4cf025_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('event', 'p1', 'p2'), name='uniq_match_pair'),
        ),
        migrations.AddConstraint(
            model_name='signal',
            constraint=models.UniqueConstraint(fields=('event', 'from_participant', 'to_participant'), name='uniq_signal'),
        ),

    ]
