# Generated by Django 6.0.2 on 2026-02-10 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='uniq_match_pair',
        ),
        migrations.RemoveConstraint(
            model_name='participant',
            name='uniq_event_nickname',
        ),
        migrations.RemoveConstraint(
            model_name='signal',
            name='uniq_signal',
        ),
        migrations.RemoveConstraint(
            model_name='signal',
            name='no_self_signal',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='game_messag_event_i_4cf025_idx',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='message_open',
            new_name='message_write_open',
        ),
        migrations.AddField(
            model_name='event',
            name='message_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='p1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_p1', to='game.participant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='p2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_p2', to='game.participant'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='pin_hash',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='participant',
            name='received_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='signal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('event', 'p1', 'p2')},
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('event', 'from_participant')},
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('event', 'nickname')},
        ),
    ]
